configurations:
  database:
    url: postgresql+asyncpg://
    echo: true
    user: 
    password: 
    host: 
    port: 5432
    dbname:
    pool_size: 5
    pool_size_overflow: 10

  hh:
    api_url: https://api.hh.ru
    user_agent: 
    token: 

  deepseek:
    model_name: deepseek-chat
    max_tokens: 1000
    temperature: 0.7
    top_p: 0.9
    frequency_penalty: 0.0
    presence_penalty: 0.0
    deepseek: 
    
  debug: false 